config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :sozees, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create, :edit, :update, :destroy]
  end
  get :dashboard, to: "users#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :sozee
  validates :location, :day, :start_time, :end_time, presence: true
end

app/models/sozee.rb
class Sozee < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :user
  mount_uploader :photo, PhotoUploader
  validates :sozee_of, :sozee_name, :category, :photo, :price_per_hour, presence: true
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :sozees, dependent: :destroy
  has_many :bookings, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # [...]
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :dashboard], unless: :skip_pundit?
  #after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :city, :email, :password) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :city) }
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @sozee = Sozee.find(params[:sozee_id])
    @user = current_user
    @booking = Booking.new
    authorize @booking
  end

  def create
    @sozee = Sozee.find(params[:sozee_id])
    @booking = Booking.new(booking_params)
    @booking.sozee = @sozee
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to sozee_path(@sozee), notice: 'Votre demande de réservation a bien été envoyée.'
    else
      render :new
    end
  end

  def edit
    @booking = booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    authorize @booking
    redirect_to dashboard_path, notice: 'Votre demande a bien été prise en compte.'
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    authorize @booking
    redirect_to dashboard_path, notice: 'Votre demande de suppression a bien été prise en compte.'
  end

  private

  def booking_params
    params.require(:booking).permit(:sozee_id, :user_id, :location, :day, :start_time, :end_time, :status, :bookingmessage)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/sozees_controller.rb
class SozeesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = " \
        sozees.sozee_of @@ :query \
        OR sozees.category @@ :query \
        OR sozees.sozee_name @@ :query \
        OR users.username @@ :query \
        OR users.city @@ :query \
      "
      @sozees = Sozee.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    else
      @sozees = Sozee.where.not(latitude: nil, longitude: nil)
    end
    @markers = @sozees.map do |sozee|
      {
        lat: sozee.latitude,
        lng: sozee.longitude,
        # icon: sozee.photo,
        # height: 20%

        infoWindow: { content: render_to_string(partial: "/sozees/map_box", locals: { sozee: sozee }) }
      }
    end
  end

  def new
    @sozee = Sozee.new
    authorize @sozee
  end

  def show
    @sozee = Sozee.find(params[:id])
    @booking = Booking.new
    authorize @sozee
  end

  def create
    @sozee = Sozee.new(sozee_params)
    @sozee.user = current_user
    authorize @sozee
    if @sozee.save
      redirect_to sozee_path(@sozee), notice: 'Your annonce was successfully created.'
    else
      render :new
    end
  end

  def destroy       # DELETE /sozees/:id
    @sozee = Sozee.find(params[:id])
    authorize @sozee
    @sozee.destroy
    redirect_to sozees_path
  end

  private

  def sozee_params
    params.require(:sozee).permit(:sozee_of, :sozee_name, :category, :description, :address, :category, :price_per_hour, :photo, :id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def dahsboard
   @sozee = current_user.sozees.first
   # mes reservations en tant que sozee
   # mes reservations en tant que user

   # authorize @user
 end

  def index
    @users = User.where.not(latitude: nil, longitude: nil)

    @markers = @users.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<div class="booking">

<%= simple_form_for ([ sozee, booking ]) do |f| %>
  <%= f.input :location, :label => "Lieu de votre animation", class: "location" %>
  <%= f.input :day, :label => "Jours de réservation", as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :start_time, :label => "Heure de début", collection: %w(00:30 01:00 01:30 02:00 02:30  03:00 03:30 04:00 04:30 05:00 05:30 06:00 06:30 07:00 07:30 08:00 08:30 09:00 09:30 10:00 10:30 11:00 11:30 12:00 12:30 13:00 13:30 14:00 14:30 15:00 15:30 16:00 16:30 17:00 17:30 18:00 18:30 19:00 19:30 20:00 20:30 21:00 21:30 22:00 22:30 23:00 23:30 00:00) %>
  <%= f.input :end_time, :label => "Heure de fin", collection: %w(00:30 01:00 01:30 02:00 02:30  03:00 03:30 04:00 04:30 05:00 05:30 06:00 06:30 07:00 07:30 08:00 08:30 09:00 09:30 10:00 10:30 11:00 11:30 12:00 12:30 13:00 13:30 14:00 14:30 15:00 15:30 16:00 16:30 17:00 17:30 18:00 18:30 19:00 19:30 20:00 20:30 21:00 21:30 22:00 22:30 23:00 23:30) %>
  <%= f.input :bookingmessage, :label => "Commentaire ", placeholder: "Précisez l'occasion pour laquelle vous souhaitez réserver le sozee" %>
  <%= f.submit "Envoyer ma demande", class: "bouton" %>
<% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

      <%= simple_form_for ([ @sozee, @user, @booking ]) do |f| %>
        <%= f.input :location %>
        <%= f.input :starts_at %>
        <%= f.input :ends_at %>
        <%= f.submit "Book this sozee !", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sozee</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>

    <div class="wrapper">
      <%= yield %>
    </div>

    <%= render "shared/footer" %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %> <!-- add this line -->
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "johnny.jpg" %>');">
  <div class="banner-content">
    <h1> Louez votre idole. </h1>

      <!-- typed.js -->
      <div class="typed">
        <p>Parce que vous méritez tous d'avoir le sozee de &nbsp;</p><div id="banner-typed-text"></div><p>| pour animer votre soirée.</p>
      </div>


    <div class="text-center padded">
    <%= link_to "Réserver", sozees_path, class: "btn-home" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to sozees_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_sozee.png", class: "logo" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? && current_user.sozees.empty? %>
      <!-- Links when logged in -->
      <%= link_to "Devenir sozee", new_sozee_path, class: "navbar-wagon-item navbar-wagon-link", id:"devenir" %>
      <!-- Avatar with dropdown menu -->
        <%= link_to dashboard_path, class: "navbar-wagon-item navbar-wagon-link" do %>
          <%= t(".profile", default: "Mon profil") %>
        <% end %>
        <%= link_to destroy_user_session_path,class: "navbar-wagon-item navbar-wagon-link", method: :delete do %>
          <%= t(".sign_out", default: "Déconnexion") %>
        <% end %>
        <div class="dropdown">

          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to current_user.username%></li>
          </ul>
        </div>
    <!-- si le user est un sozee (pas de bouton devenir sozee) -->
    <% elsif user_signed_in? && !current_user.sozees.empty? %>
        <%= link_to dashboard_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <%= t(".profile", default: "Mon profil") %>
        <% end %>
        <%= link_to destroy_user_session_path,class: "navbar-wagon-item navbar-wagon-link", method: :delete do %>
        <%= t(".sign_out", default: "Déconnexion") %>
        <% end %>
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to current_user.username%></li>
          </ul>
        </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Devenir sozee", new_user_session_path, id: "devenir" %>
      <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Inscription"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? && current_user.sozees.empty? %>
          <li><%= link_to current_user.username%></li>
          <li><%= link_to "Devenir sozee", new_sozee_path %></li>
          <li><%= link_to "Mon profil", dashboard_path %></li>
          <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
        <% elsif user_signed_in? && !current_user.sozees.empty? %>
          <li><%= link_to current_user.username%></li>
          <li><%= link_to "Mon profil", dashboard_path %></li>
          <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Devenir sozee", new_sozee_path %></li>
          <li><%= link_to "Connexion", new_user_session_path %></li>
          <li><%= link_to "Inscription", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_old_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="http://www.espacekid.com/images/Coloriage/670-coloriage-masque-double.gif" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? == true %>
      <li><%= link_to "Devenir sozee", new_sozee_path %></li>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
      <% end %>

    <% else %>
      <li><%= link_to "Devenir sozee", new_sozee_path %></li>
      <li><%= link_to "Connexion", new_user_session_path %></li>
      <li><%= link_to "Inscription", new_user_registration_path %></li>
    <% end %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if user_signed_in? == true %>
          <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% else %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% if user_signed_in? == true %>
            <li><%= link_to "Devenir sozee", new_sozee_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path %></li>
          <% else %>
            <li><%= link_to "Devenir sozee", new_sozee_path %></li>
            <li><%= link_to "Connexion", new_user_session_path %></li>
            <li><%= link_to "Inscription", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? == true %>
          <li><%= link_to "Devenir sozee", new_sozee_path %></li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        <% else %>
          <li><%= link_to "Devenir sozee", new_sozee_path %></li>
          <li><%= link_to "Connexion", new_user_session_path %></li>
          <li><%= link_to "Inscription", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="images/logo.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/sozees/_map_box.html.erb
<h5><b><%= sozee.sozee_name%></b></h5>
<h6><%= sozee.price_per_hour %> €/heure</h6>
<p>Sozee de : <font color=#617CEC><%= sozee.sozee_of %></p></font>
<br>
<center><%= link_to "Réserver", sozee_path(sozee), class: "btn-home" %></center>
<br>

app/views/sozees/index.html.erb
<div class="main-container">
  <div class="cards-container">
    <%= form_tag sozees_path, class: "search-form" , method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search-loop",
        placeholder: "Nom, catégorie, ville"
      %>
    <% end %>
    <% @sozees.each do |sozee| %>
    <div class="col-xs-12 col-sm-6 col-lg-6">
      <div class="main-card-index">
       <div class="card-index" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path sozee.photo %>')";>
        <!-- , crop: :thumb, gravity: :face -->
        <div class="card-category-index"><%= sozee.user.city %></div>
       </div> <!-- card index -->
       <div class="card-info-index">
        <div class="card-description-index">
          <h2><%= sozee.sozee_name %></h2>
          <p><%= sozee.sozee_of %></p>
        </div><!--  card description -->
        <div class="price">
          <p><%=sozee.category%></p>
          <p><i class="fa fa-eur" aria-hidden="true"></i> <%= sozee.price_per_hour %>/h</p>
          <%= link_to "", sozee_path(sozee), class: "full-card-link" %>
        </div> <!-- price -->
       </div> <!-- card info index -->
      </div> <!-- main card index -->
    </div> <!-- col -->
    <!-- <a class="card-link-index" href="#" ></a> -->
    <% end %>
  </div> <!-- cards-container -->
  <div
    id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>"
  ></div>


</div> <!-- main-container -->

app/views/sozees/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">

      <h1>Deviens un sozee</h1>
      <%= simple_form_for @sozee do |f| %>
        <%= f.input :sozee_of, :label => "De qui êtes vous le sozee ?", input_html: { class: "form-control", required: false } %>
        <%= f.input :sozee_name, :label => "Quel est votre nom de scène ?", input_html: { class: "form-control", required: false } %>
        <%= f.input :category, :label => "Catégorie", collection: ["Cinéma", "Musique", "Politique", "Histoire", "Sport", "Autre"], input_html: { class: "form-control", required: false } %>
        <%= f.input :address, as: :hidden, input_html: { value: current_user.city } %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :description, :label => "Décrivez vos services !" %>
        <%= f.input :price_per_hour, :label => "Prix par heures", input_html: { min: '0', step: 'any' }%>
        <%= f.submit "Devenir sozee !", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/sozees/show.html.erb
<div class="container">
  <div class="container-show">
    <div class="card-show">
      <div id="card-show-image">
        <%= cl_image_tag @sozee.photo, class: "card-user", crop: :fill%>
      </div>
      <div class="card-show-infos">
        <div id="first-element-card" class="flexbox">
          <div>
            <h3><%= @sozee.sozee_name %></h3>
            <p>Sozee de <%= @sozee.sozee_of %></p>
          </div>
          <div>
            <h3 id="sozee-price-show"><%= @sozee.price_per_hour %>€<p>de l'heure</p></h3>
          </div>
        </div>
        <div class="text-center">
          <p>"<%= @sozee.description %>"</p>
        </div>
        <div id="reviews-container">
          <div>
            <h4><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star-half-o" aria-hidden="true"></i></h4>
            <p class="review-category"><strong>Ressemblance physique</strong></p>
          </div>
          <div>
            <h4><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star-half-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i></h4>
            <p class="review-category"><strong>Imitation</strong></p>
          </div>
          <div>
            <h4><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i></h4>
            <p class="review-category" ><strong>Animation</strong></p>
          </div>
        </div>
      </div>
    </div>

    <div class="info-show">

      <% if user_signed_in? == false %>
        <%= link_to "Inscris toi pour booker ce sozee !", new_user_registration_path, class: "btn btn-primary" %>

      <% elsif !@sozee.bookings.where("user_id = ?", current_user.id).empty? %>

        <div class="booking-info-show">
            <p>Demande de réservation <%= link_to "en cours", dashboard_path %> pour ce sozee.</p>
        </div>
            <h3 id="new-booking-title">Nouvelle réservation</h3>
          <div class="new-booking-form">
            <%= render "bookings/new", sozee: @sozee, booking: @booking %>
        </div>

      <% elsif @sozee.user_id == @current_user.id %>
        <div class="booking-info-show">
          <p>Ceci est votre annonce telle que vu par les utilisateurs. <%= link_to "Gérer mes réservations", dashboard_path %></p>
        </div>
        <br>
          <h3 id="new-booking-title">Réservez ce sozee !</h3>
          <div class="form-container-show">
            <%= render "bookings/new", sozee: @sozee, booking: @booking %>
        </div>

      <% else %>
        <h3 id="title-info-show">Réservez ce sozee !</h3>
        <div class="form-container-show">
          <%= render "bookings/new", sozee: @sozee, booking: @booking %>
        </div>
      <% end %>
    </div>
  </div>
</div>